language: generic

sudo: required


services:
  - docker

before_install:
  - docker build -t dd1331/movement-server-test -f Dockerfile.dev .

script:
  # - docker run -e CI=true dd1331/movement-server-test npm run test -- --coverage

after_success:
  - echo "test succeed!"
  - docker build -t dd1331/movement-server ./
  - docker build -t dd1331/movement-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push dd1331/movement-server
  - docker push dd1331/movement-nginx

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "movement-server"
  env: "Movementserver-env"
  bucket_name: elasticbeanstalk-ap-northeast-2-145358528946
  bucket_path: "movement-server"
  on:
    branch: main
  
  access_key_id: $AWS_ACCESS_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
