version: "3"
services: 
  # frontend:
     # build:
       # dockerfile: blahblah
       # context: blahblah
     # volumes: 
       # - blahblah
       # - blahblah
     # stdin_open: true

  redis:
    image: "redis"
    container_name: redis-server
    ports: 
      - "6379:6379"
  # comment out for now in local
  nginx:
    restart: always
    build: 
      dockerfile: Dockerfile
      context: ./nginx
    ports: 
      - "3000:80"

  backend:
    build: 
      dockerfile: Dockerfile.dev
      # for main app. it was ./backend
      context: ./
    container_name: backend
    volumes: 
      - /app/node_modules
      # for main app. it was ./backend
      - ./:/app
    environment: 
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: a9884592
      MYSQL_DATABASE: movement
      MYSQL_PORT: 3306
      
  

  # mysql:
  #   image: "mysql:5.7.24"
  #   container_name: "typeorm-mysql"
  #   ports:
  #     - "3306:3306"
  #   command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
  #   volumes: 
  #     - ./mysql/mysql_data:/var/lib/mysql
  #     - ./mysql/sqls/:/docker-entrypoint-initdb.d/
  #   environment:
  #     MYSQL_ROOT_PASSWORD: "a9884592"
  #     MYSQL_USER: "charlie"
  #     MYSQL_PASSWORD: "1331"
  #     MYSQL_DATABASE: "movement"

